version: '3.8' # Specify docker-compose version

services:
  # Frontend Service (Angular App served by Nginx)
  frontend:
    build:
      context: . # Use the current directory for build context
      dockerfile: Dockerfile # Specify the frontend Dockerfile
    container_name: agenda-frontend
    ports:
      - "8080:80" # Map host port 8080 to container port 80 (Nginx)
    depends_on:
      - backend # Ensure backend starts before frontend (doesn't guarantee readiness)
    networks:
      - agenda-network

  # Backend Service (JSON Server)
  backend:
    build:
      context: . # Use the current directory for build context
      dockerfile: Dockerfile.backend # Specify the backend Dockerfile
    container_name: agenda-backend
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000 (json-server)
    volumes:
      # Mapeia o VOLUME NOMEADO para /app dentro do container
      - agenda_db_data:/app
    networks:
      - agenda-network

# Define the network
networks:
  agenda-network:
    driver: bridge

# --- ADICIONADO: Declaração do volume nomeado ---
volumes:
  agenda_db_data:
