# VERSÃO DA SINTAXE DO COMPOSE
version: '3.8'

# DEFINE OS CONTAINERS (SERVIÇOS)
services:
  # SERVIÇO DO FRONTEND (Angular + Nginx)
  frontend:
    build:
      context: . # Diretório atual como contexto para build
      dockerfile: Dockerfile # Dockerfile do frontend
    container_name: agenda-frontend # Nome do container
    ports: # MAPEAMENTO DE PORTAS (Host:Container)
      - "8080:80" # Mapeia porta 8080 do PC para porta 80 do container (Nginx)
    depends_on: # DEPENDÊNCIAS DE INICIALIZAÇÃO
      - backend # Inicia 'backend' antes de 'frontend'
    networks: # REDES DO CONTAINER
      - agenda-network # Conecta à rede 'agenda-network'

  # SERVIÇO DO BACKEND (JSON Server)
  backend:
    build:
      context: . # Diretório atual como contexto para build
      dockerfile: Dockerfile.backend # Dockerfile do backend
    container_name: agenda-backend # Nome do container
    ports: # MAPEAMENTO DE PORTAS (Host:Container)
      - "3000:3000" # Mapeia porta 3000 do PC para porta 3000 do container (json-server)
    volumes: # VOLUMES (ARMAZENAMENTO PERSISTENTE)
      # Mapeia o VOLUME NOMEADO 'agenda_db_data' para /app no container
      - agenda_db_data:/app # Garante persistência do db.json e evita erros EBUSY
    networks: # REDES DO CONTAINER
      - agenda-network # Conecta à rede 'agenda-network'

# DEFINE A REDE CUSTOMIZADA
networks:
  agenda-network:
    driver: bridge # Usa o driver de rede padrão 'bridge'

# DECLARA O VOLUME NOMEADO
volumes:
  agenda_db_data: # Define um volume gerenciado pelo Docker chamado 'agenda_db_data'
